// Generated by Wrangler on Sun Jul 28 2024 09:05:24 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

export interface Env {
	AI: Ai;
	ANALYTICS_ENGINE?: AnalyticsEngine;
}

export interface AnalyticsEngine {
	write: (data: {
		localHour: number;
		[key: string]: unknown;
	}) => Promise<void>;
}
